branches:
  only:
    - master

stages:
  - lint
  - builds

matrix:
  include:
    # Lint
    - stage: lint
      language: node_js
      os: linux
      node_js: '8'
      script:
        - cd src && npm run ci.tslint
        - cd ../demo && npm run ci.tslint
    - stage: builds
      ## Android Build
      os: linux
      env:
        - OS="Android28"
      language: android
      jdk: oraclejdk8
      before_install: nvm install 8.11.4
      script:
        - cd src && npm i && npm run tsc
        - cd ../demo && tns build android
    ## iOS Build
    - os: osx
      env:
        - OS="iOS12.0"
        - Xcode="10.1"
      osx_image: xcode10.1
      language: node_js
      node_js: '8'
      jdk: oraclejdk8
      script:
        - cd src && npm i && npm run tsc
        - cd ../demo && tns build ios
      ## Android Webpack Core
    - os: linux
      language: android
      env:
        - OS="Android28"
      jdk: oraclejdk8
      before_install: nvm install 8.11.4
      script:
        - cd demo && npm run build.plugin
        - npm i && tns build android --bundle --env.uglify
    # iOS Webpack Core
    - os: osx
      env:
        - OS="iOS12.0"
        - Xcode="10.1"
      osx_image: xcode10.1
      language: node_js
      node_js: '8'
      jdk: oraclejdk8
      script:
        - cd demo && npm run build.plugin
        - npm i && tns build ios --bundle --env.uglify
      ## Android Angular Webpack
    - env:
        - OS="Android28"
      before_install: 'nvm install 8.11.4'
      jdk: oraclejdk8
      language: android
      os: linux
      script:
        - cd src && npm run build && npm pack
        - cd ../demo-angular && tns plugin add ../src/*.tgz
        - npm i && tns build android --bundle --env.uglify --env.aot
    ## iOS Angular Webpack
    - env:
        - OS="iOS12.0"
        - Xcode="10.1"
      jdk: oraclejdk8
      language: node_js
      node_js: '8'
      os: osx
      osx_image: xcode10.1
      script:
        - cd src && npm run build && npm pack
        - cd ../demo-angular && tns plugin add ../src/*.tgz
        - npm i && tns build ios --bundle --env.uglify --env.aot
      ## Android Vue Webpack
    - env:
        - OS="Android28"
      before_install: 'nvm install 8.11.4'
      jdk: oraclejdk8
      language: android
      os: linux
      script:
        - cd demo-vue && npm run build.plugin
        - npm i && tns build android --bundle --env.uglify
    ## iOS Vue Webpack
    - env:
        - OS="iOS12.0"
        - Xcode="10.1"
      jdk: oraclejdk8
      language: node_js
      node_js: '8'
      os: osx
      osx_image: xcode10.1
      script:
        - cd demo-vue && npm run build.plugin
        - npm i && tns build ios --bundle --env.uglify
    ## Android Test
    - os: linux
      language: android
      dist: precise
      jdk: oraclejdk8
      env:
        - OS="Android28"
      before_script:
        - echo no | android create avd --force -n test -t android-21 -b armeabi-v7a
        - emulator -avd test -no-audio -no-window &
        - android-wait-for-emulator
      before_install:
        - nvm install 8
      script:
        - cd src && npm i && npm run tsc && npm run tslint && cd ../demo && tns build android
        - travis_wait travis_retry tns test android --justlaunch
    ## iOS Test
    - os: osx
      language: node_js
      node_js: '8'
      jdk: oraclejdk8
      env:
        - OS="iOS12.0"
        - Xcode="10.1"
      osx_image: xcode10.1
      script:
        - cd src && npm i && npm run tsc && npm run tslint && cd ../demo && tns build ios
        - travis_wait travis_retry tns test ios --justlaunch

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21

before_install:
  - sudo pip install --upgrade pip
  - sudo pip install six

install:
  - echo no | npm install -g nativescript
  - tns usage-reporting disable
  - tns error-reporting disable
